cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED WORK_DIR OR WORK_DIR STREQUAL "")
    message(FATAL_ERROR "Missing -DWORK_DIR=...")
endif()
# 每次使用新的测试夹具，避免删除或覆盖其他构建产物。
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef fixture_id)
set(stage "${WORK_DIR}/${fixture_id}")
file(MAKE_DIRECTORY "${stage}")
set(version 1.2.3)
set(commit aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)
set(manifest_script "${CMAKE_CURRENT_LIST_DIR}/../release-manifest.cmake")
set(archives "")
foreach(platform linux-x64-gcc linux-arm64-gcc windows-x64-msvc macos-x64-appleclang macos-arm64-appleclang)
    if(platform MATCHES "^windows-")
        set(extension zip)
    else()
        set(extension tar.gz)
    endif()
    foreach(linkage static shared)
        set(filename "dlt698-${version}-${platform}-${linkage}.${extension}")
        # 此处只测发布矩阵和校验门槛；真实压缩包由安装消费方测试及发布打包步骤验证。
        file(WRITE "${stage}/${filename}" "fixture ${platform} ${linkage}\n")
        file(SHA256 "${stage}/${filename}" digest)
        file(WRITE "${stage}/${filename}.sha256" "${digest}  ${filename}\n")
        list(APPEND archives "${filename}")
    endforeach()
endforeach()

function(check_manifest expected_error)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DASSET_DIR=${stage}"
        "-DRELEASE_VERSION=${version}" "-DRELEASE_COMMIT=${commit}" -P "${manifest_script}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expected_error STREQUAL "")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Valid C++ matrix rejected: ${output}\n${error}")
        endif()
    elseif(result EQUAL 0 OR NOT "${error}" MATCHES "${expected_error}")
        message(FATAL_ERROR "Expected rejection '${expected_error}', got ${result}: ${output}\n${error}")
    endif()
endfunction()

check_manifest("")
# 原目录可重复生成，清单与校验和自身不得被当作额外制品。
check_manifest("")
file(READ "${stage}/release-manifest.json" manifest)
string(JSON actual_version GET "${manifest}" version)
string(JSON actual_commit GET "${manifest}" commit)
string(JSON artifact_count LENGTH "${manifest}" artifacts)
if(NOT actual_version STREQUAL version OR NOT actual_commit STREQUAL commit OR NOT artifact_count EQUAL 10)
    message(FATAL_ERROR "Invalid C++ manifest identity or artifact count")
endif()
file(STRINGS "${stage}/SHA256SUMS" checksums)
list(LENGTH checksums checksum_count)
if(NOT checksum_count EQUAL 21)
    message(FATAL_ERROR "SHA256SUMS must cover ten archives, ten sidecars and the manifest")
endif()
foreach(line IN LISTS checksums)
    string(SUBSTRING "${line}" 0 64 expected_digest)
    string(SUBSTRING "${line}" 66 -1 filename)
    file(SHA256 "${stage}/${filename}" actual_digest)
    if(NOT expected_digest STREQUAL actual_digest)
        message(FATAL_ERROR "Invalid checksum entry: ${filename}")
    endif()
endforeach()

list(GET archives 0 filename)
file(READ "${stage}/${filename}" payload)
file(REMOVE "${stage}/${filename}")
check_manifest("Incomplete C\\+\\+ SDK release")
file(WRITE "${stage}/${filename}" "${payload}tampered")
check_manifest("checksum mismatch")
file(WRITE "${stage}/${filename}" "${payload}")
file(READ "${stage}/${filename}.sha256" sidecar)
file(REMOVE "${stage}/${filename}.sha256")
check_manifest("Incomplete C\\+\\+ SDK release")
file(WRITE "${stage}/${filename}.sha256" "${sidecar}")
foreach(unexpected "dlt698-${version}.tar.gz" "dlt698-${version}-cp311-cp311-win_amd64.whl"
    "dlt698-9.9.9-windows-x64-msvc-static.zip")
    file(WRITE "${stage}/${unexpected}" "unrelated distribution")
    check_manifest("Unexpected release asset")
    file(REMOVE "${stage}/${unexpected}")
endforeach()
set(commit invalid)
check_manifest("full Git commit hash")
message(STATUS "C++ release manifest acceptance and rejection checks passed")
