add_executable(dlt698_decode decode.cpp)
add_executable(dlt698_standard_points standard_points.cpp)
target_link_libraries(dlt698_standard_points PRIVATE dlt698_service)
dlt698_target_setup(dlt698_standard_points)
add_executable(dlt698_standard_points_extended standard_points_extended.cpp)
target_link_libraries(dlt698_standard_points_extended PRIVATE dlt698_service)
dlt698_target_setup(dlt698_standard_points_extended)
target_link_libraries(dlt698_decode PRIVATE dlt698_core)
dlt698_target_setup(dlt698_decode)
add_executable(dlt698_memory_get memory_get.cpp)
target_link_libraries(dlt698_memory_get PRIVATE dlt698_service)
dlt698_target_setup(dlt698_memory_get)
add_executable(dlt698_memory_mutation memory_mutation.cpp)
target_link_libraries(dlt698_memory_mutation PRIVATE dlt698_service)
dlt698_target_setup(dlt698_memory_mutation)
if(DLT698_BUILD_TRANSPORT)
    add_executable(dlt698_master peer.cpp)
    target_link_libraries(dlt698_master PRIVATE dlt698_service dlt698_transport)
    dlt698_target_setup(dlt698_master)
    add_executable(dlt698_terminal peer.cpp)
    target_compile_definitions(dlt698_terminal PRIVATE DLT698_TERMINAL)
    target_link_libraries(dlt698_terminal PRIVATE dlt698_service dlt698_transport)
    dlt698_target_setup(dlt698_terminal)
endif()
