add_executable(dlt698_decode decode.cpp)
target_link_libraries(dlt698_decode PRIVATE dlt698_core)
dlt698_target_setup(dlt698_decode)
add_executable(dlt698_memory_get memory_get.cpp)
target_link_libraries(dlt698_memory_get PRIVATE dlt698_service)
dlt698_target_setup(dlt698_memory_get)
add_executable(dlt698_memory_mutation memory_mutation.cpp)
target_link_libraries(dlt698_memory_mutation PRIVATE dlt698_service)
dlt698_target_setup(dlt698_memory_mutation)
