cmake_minimum_required(VERSION 3.20)

# 发布只接受完整的 C++ SDK 矩阵，避免 Python sdist 或 wheel 混入附件。
foreach(argument ASSET_DIR RELEASE_VERSION RELEASE_COMMIT)
    if(NOT DEFINED ${argument} OR "${${argument}}" STREQUAL "")
        message(FATAL_ERROR "Missing -D${argument}=...")
    endif()
endforeach()
if(NOT RELEASE_VERSION MATCHES "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")
    message(FATAL_ERROR "RELEASE_VERSION must be X.Y.Z")
endif()
string(LENGTH "${RELEASE_COMMIT}" commit_length)
if(NOT commit_length EQUAL 40 OR NOT RELEASE_COMMIT MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "RELEASE_COMMIT must be a full Git commit hash")
endif()
get_filename_component(ASSET_DIR "${ASSET_DIR}" ABSOLUTE)
set(platforms linux-x64-gcc linux-arm64-gcc windows-x64-msvc macos-x64-appleclang macos-arm64-appleclang)
set(expected_files "")
set(checksums "")
set(records "")
foreach(platform IN LISTS platforms)
    if(platform MATCHES "^windows-")
        set(extension zip)
    else()
        set(extension tar.gz)
    endif()
    foreach(linkage static shared)
        set(filename "dlt698-${RELEASE_VERSION}-${platform}-${linkage}.${extension}")
        foreach(required_file "${filename}" "${filename}.sha256")
            if(NOT EXISTS "${ASSET_DIR}/${required_file}" OR IS_DIRECTORY "${ASSET_DIR}/${required_file}")
                message(FATAL_ERROR "Incomplete C++ SDK release: ${required_file}")
            endif()
            list(APPEND expected_files "${required_file}")
        endforeach()
        file(SHA256 "${ASSET_DIR}/${filename}" digest)
        file(READ "${ASSET_DIR}/${filename}.sha256" recorded_checksum)
        if(NOT recorded_checksum STREQUAL "${digest}  ${filename}\n")
            message(FATAL_ERROR "C++ SDK checksum mismatch: ${filename}")
        endif()
        string(APPEND checksums "${digest}  ${filename}\n")
        file(SHA256 "${ASSET_DIR}/${filename}.sha256" checksum_digest)
        string(APPEND checksums "${checksum_digest}  ${filename}.sha256\n")
        if(NOT records STREQUAL "")
            string(APPEND records ",\n")
        endif()
        string(APPEND records
            "    {\"filename\": \"${filename}\", \"platform\": \"${platform}\", \"linkage\": \"${linkage}\", \"sha256\": \"${digest}\"}")
    endforeach()
endforeach()
# 允许同一目录重新生成清单，但不接受其他版本、库类型或无关文件。
list(APPEND expected_files release-manifest.json SHA256SUMS)
file(GLOB actual_files RELATIVE "${ASSET_DIR}" "${ASSET_DIR}/*")
foreach(filename IN LISTS actual_files)
    if(NOT filename IN_LIST expected_files)
        message(FATAL_ERROR "Unexpected release asset: ${filename}")
    endif()
endforeach()
file(WRITE "${ASSET_DIR}/release-manifest.json"
    "{\n  \"schema\": 1,\n  \"version\": \"${RELEASE_VERSION}\",\n  \"commit\": \"${RELEASE_COMMIT}\",\n  \"artifacts\": [\n${records}\n  ]\n}\n")
file(SHA256 "${ASSET_DIR}/release-manifest.json" manifest_digest)
file(WRITE "${ASSET_DIR}/SHA256SUMS" "${checksums}${manifest_digest}  release-manifest.json\n")
message(STATUS "Verified 10 C++ SDK archives; generated release-manifest.json and SHA256SUMS")
