cmake_minimum_required(VERSION 3.20)

# 使用 cmake --install 的布局，确保发布包与 find_package 导出保持一致。
foreach(argument BUILD_DIR OUTPUT_DIR PLATFORM LINKAGE)
    if(NOT DEFINED ${argument} OR "${${argument}}" STREQUAL "")
        message(FATAL_ERROR "Missing -D${argument}=...")
    endif()
endforeach()
if(NOT LINKAGE MATCHES "^(static|shared)$")
    message(FATAL_ERROR "LINKAGE must be static or shared")
endif()
if(NOT PLATFORM MATCHES "^(linux-(x64|arm64)-gcc|windows-x64-msvc|macos-(x64|arm64)-appleclang)$")
    message(FATAL_ERROR "Unsupported release PLATFORM: ${PLATFORM}")
endif()
get_filename_component(BUILD_DIR "${BUILD_DIR}" ABSOLUTE)
get_filename_component(OUTPUT_DIR "${OUTPUT_DIR}" ABSOLUTE)
get_filename_component(source_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(STRINGS "${BUILD_DIR}/CMakeCache.txt" shared_cache REGEX "^BUILD_SHARED_LIBS:[^=]+=.*$")
string(REGEX REPLACE "^[^=]+=" "" built_shared "${shared_cache}")
if(shared_cache STREQUAL "")
    message(FATAL_ERROR "BUILD_SHARED_LIBS must be explicitly configured")
endif()
if((LINKAGE STREQUAL "shared" AND NOT built_shared) OR (LINKAGE STREQUAL "static" AND built_shared))
    message(FATAL_ERROR "LINKAGE does not match the configured BUILD_SHARED_LIBS")
endif()
file(READ "${source_dir}/VERSION" version)
string(STRIP "${version}" version)
if(NOT version MATCHES "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")
    message(FATAL_ERROR "VERSION must contain a single X.Y.Z version")
endif()
set(package_name "dlt698-${version}-${PLATFORM}-${LINKAGE}")
set(stage "${BUILD_DIR}/release-stage/${package_name}")
# 不复用旧的安装目录，避免已删除的头文件或另一种库混入本次产物。
if(EXISTS "${stage}")
    message(FATAL_ERROR "Package stage already exists; use a fresh BUILD_DIR: ${stage}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" --install "${BUILD_DIR}" --config Release --prefix "${stage}"
    RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Release installation failed: ${result}")
endif()

if(NOT EXISTS "${stage}/include/dlt698/export.hpp")
    message(FATAL_ERROR "Missing public export header: export.hpp")
endif()
if(PLATFORM MATCHES "^windows-")
    set(library "${stage}/lib/dlt698.lib")
    if(LINKAGE STREQUAL "shared" AND NOT EXISTS "${stage}/bin/dlt698.dll")
        message(FATAL_ERROR "Missing runtime DLL: dlt698.dll")
    endif()
elseif(LINKAGE STREQUAL "static")
    set(library "${stage}/lib/libdlt698.a")
elseif(PLATFORM MATCHES "^macos-")
    set(library "${stage}/lib/libdlt698.dylib")
else()
    set(library "${stage}/lib/libdlt698.so")
endif()
if(NOT EXISTS "${library}")
    message(FATAL_ERROR "Missing release library: ${library}")
endif()
foreach(required_file include/dlt698/app.hpp include/dlt698/transport/tcp.hpp
    include/dlt698/transport/serial.hpp lib/cmake/dlt698/dlt698Config.cmake
    lib/cmake/dlt698/dlt698ConfigVersion.cmake lib/cmake/dlt698/dlt698Targets.cmake
    share/dlt698/LICENSE share/dlt698/ASIO_LICENSE_1_0.txt)
    if(NOT EXISTS "${stage}/${required_file}")
        message(FATAL_ERROR "Incomplete release package: ${required_file}")
    endif()
endforeach()
file(STRINGS "${stage}/lib/cmake/dlt698/dlt698ConfigVersion.cmake" installed_version
    REGEX "^set\\(PACKAGE_VERSION ")
if(NOT installed_version STREQUAL "set(PACKAGE_VERSION \"${version}\")")
    message(FATAL_ERROR "Installed library version does not match VERSION; reconfigure and rebuild")
endif()
file(COPY "${source_dir}/VERSION" "${source_dir}/README.md" DESTINATION "${stage}")

# Unix 使用 tar.gz 保留版本化共享库的符号链接，Windows 使用 zip。
if(PLATFORM MATCHES "^windows-")
    set(archive "${OUTPUT_DIR}/${package_name}.zip")
    set(tar_options cf)
    set(format --format=zip)
else()
    set(archive "${OUTPUT_DIR}/${package_name}.tar.gz")
    set(tar_options czf)
    set(format --format=gnutar)
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar ${tar_options} "${archive}" ${format} "${package_name}"
    WORKING_DIRECTORY "${BUILD_DIR}/release-stage" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Release archive failed: ${result}")
endif()
file(SHA256 "${archive}" checksum)
get_filename_component(archive_name "${archive}" NAME)
file(WRITE "${archive}.sha256" "${checksum}  ${archive_name}\n")
message(STATUS "Release package: ${archive}")
